version: '3.9'

services:
  db-test:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: donation_api_test

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: donation_api_development

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create db:migrate && rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db/donation_api_development

  test:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create db:migrate && bundle exec rspec"
    volumes:
      - .:/app
    depends_on:
      - db-test
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@db-test/donation_api_test

volumes:
  postgres_data_dev:
  postgres_data_test:
