default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>
  database: <%= ENV.fetch('POSTGRES_DB', 'donation_api_development') %>

development:
  <<: *default

test:
  <<: *default
  database: donation_api_test

production:
  <<: *default
  database: donation_api_production
